In [14]:
from pathlib import Path
import pandas as pd

RAIZ = Path.cwd().parents[0]

df_plan_de_compras = pd.read_excel(RAIZ / "plan_de_compras_2025.xlsx" , sheet_name="PLAN DE COMPRAS 2025")

df_plan_de_compras.head()

,Unidad de Compra,ID Proyecto,Tipo Proyecto,Estado Proyecto,Código presupuestario,Nombre Proyecto,Descripción Proyecto,Cantidad de Ítems,Nombre ítem,Tipo compra,...,Cargo responsable,Teléfono responsable,Correo responsable,Fecha de Inicio Compra,Fecha Publicación PAC 2025,Cantidad OC Asociadas Ítem 2025,OC Asociada Item 2025,Item De Arraste,Monto De Arrastre,Meses envio OC de Arraste
0,Ministerio de Vivienda y Urbanismo(766),587-259-PC22,Proyecto estratégico,Publicado,2207-2209-33,Servicio arriendo de una plataforma de gestión...,Servicio de arriendo de una plataforma de gest...,2,Servicio arriendo de una plataforma de gestión...,1,...,Coordinadora de Tecnologías Informáticas | Sis...,2 -2901 1198-,mzunigas@minvu.cl,2022-11-01,2022-11-08,0,NaN,1,20000000,2025-01-01
1,SEREMI MINVU V REGION,632-28-PC22,Proyecto operacional,Publicado,2206-2206001,Servicio de Mantención y Reparaciones Menores ...,Convenio de Suministro para el Servicio de Man...,1,Mantenimiento y Reparación de Edificaciones,1,...,Encargado Sección Administración y Finanzas,32-2186802-,agardaix@minvu.cl,2022-02-01,2022-11-08,1,632-7-SE22,1,4500000,2025-01-01
2,SEREMI MINVU V REGION,632-32-PC22,Proyecto operacional,Publicado,2204001,Servicios de Impresión-Seremi Valparaiso,Servicios de Impresión de Materiales SEREMI y ...,1,Materiales de Oficina,1,...,Encargado Sección Administración y Finanzas,32-2186802-,agardaix@minvu.cl,2022-08-01,2022-11-08,0,NaN,1,3825000,2025-01-01
3,SEREMI MINVU V REGION,632-34-PC22,Proyecto operacional,Publicado,2209006,Servicio de Arriendo de Impresoras Multifuncio...,Servicio de Arriendo de Impresoras Multifuncio...,2,Arriendo de Equipos Informáticos,1,...,Encargado Sección Administración y Finanzas,32-2186802-,agardaix@minvu.cl,2022-08-01,2022-11-08,1,632-13-CC23,1,4500000,2025-01-01
4,SEREMI MINVU V REGION,632-41-PC22,Proyecto operacional,Publicado,2205005,Servicio de Telefonía Fija-Seremi Valparaiso,Servicio de Telefonía Fija SEREMI,2,Telefonía Fija,1,...,Encargado Sección Administración y Finanzas,322186802,agardaix@minvu.cl,2022-12-01,2022-11-08,0,NaN,1,26400000,2025-01-01

# Análisis Exploratorio de Datos - Plan de Compras 2025

El objetivo de este notebook es realizar un análisis exploratorio del Plan de Compras 2025,
con el propósito de conocer la estructura del conjunto de datos, identificar valores
faltantes, registros duplicados, tipos de variables, distribuciones y principales
características de la información.

In [23]:
df_plan_de_compras.sample(5)

,Unidad de Compra,ID Proyecto,Tipo Proyecto,Estado Proyecto,Código presupuestario,Nombre Proyecto,Descripción Proyecto,Cantidad de Ítems,Nombre ítem,Tipo compra,...,Cargo responsable,Teléfono responsable,Correo responsable,Fecha de Inicio Compra,Fecha Publicación PAC 2025,Cantidad OC Asociadas Ítem 2025,OC Asociada Item 2025,Item De Arraste,Monto De Arrastre,Meses envio OC de Arraste
701,Ministerio de Vivienda y Urbanismo(766),1583-200-PC25,Proyecto operacional,Actualizado,2208007,ADQUISICIÓN PASAJES - SECCION GESTION DE COMPRAS,Cubrir la necesidad de traslado de los funcion...,1,ADQUISICIÓN PASAJES - SECCION GESTION DE COMPRAS,6,...,Enc. Seccion Gestión de Compras,02-29011155-,mmalhueg@minvu.cl,2025-01-01,2025-11-27,321,587-806-CM25,0,0,NaT
78,Seremi-Minvu XII Región,1657-45-PC23,Proyecto estratégico,Publicado,2209,Arriendo de impresora multifuncional_SEREMI XII,Servicio de arriendo de impresora multifuncional,2,Arriendo de impresora multifuncional,1,...,Encargada de Administración,612299503,yorellanac@minvu.cl,2023-01-01,2023-11-29,3,661-80-CC23,1,946537,2025-01-01
781,Ministerio de Vivienda y Urbanismo(766),1583-259-PC25,Proyecto operacional,Actualizado,2206001,PROVISIÓN E INSTALACIÓN DE CORTINAS - SECCION ...,"Reposición por deterioro, rotura de partes, da...",1,PROVISIÓN E INSTALACIÓN DE CORTINAS - SECCION ...,6,...,SECCION INFRAESTRUCTURA Y MANTENCION,22-901139-,jibanezt@minvu.cl,2025-05-01,2025-11-27,1,587-317-AG25,0,0,NaT
724,Ministerio de Vivienda y Urbanismo(766),1583-200-PC25,Proyecto operacional,Actualizado,2208007,ADQUISICIÓN PASAJES - SECCION GESTION DE COMPRAS,Cubrir la necesidad de traslado de los funcion...,1,ADQUISICIÓN PASAJES - SECCION GESTION DE COMPRAS,6,...,Enc. Seccion Gestión de Compras,02-29011155-,mmalhueg@minvu.cl,2025-01-01,2025-11-27,321,587-872-CM25,0,0,NaT
79,Seremi-Minvu XII Región,1657-45-PC23,Proyecto estratégico,Publicado,2209,Arriendo de impresora multifuncional_SEREMI XII,Servicio de arriendo de impresora multifuncional,2,Arriendo de impresora multifuncional,1,...,Encargada de Administración,612299503,yorellanac@minvu.cl,2023-05-01,2023-11-29,3,661-28-CC23,1,946537,2025-01-01

In [24]:
df_plan_de_compras.columns.tolist()

['Unidad de Compra',
 'ID Proyecto',
 'Tipo Proyecto',
 'Estado Proyecto',
 'Código presupuestario',
 'Nombre Proyecto',
 'Descripción Proyecto',
 'Cantidad de Ítems',
 'Nombre ítem',
 'Tipo compra',
 'Cantidad Productos',
 'Monto Unitario Ítem',
 'Monto Total Ítem Año 2025',
 'Cantidad OC',
 'Meses envío OC',
 'Nombre responsable',
 'Cargo responsable',
 'Teléfono responsable',
 'Correo responsable',
 'Fecha de Inicio Compra',
 'Fecha Publicación PAC 2025',
 'Cantidad OC Asociadas Ítem 2025',
 'OC Asociada Item 2025',
 'Item De Arraste',
 'Monto De Arrastre',
 'Meses envio OC de Arraste']

In [25]:
df_plan_de_compras.info()

<class 'pandas.DataFrame'>
RangeIndex: 831 entries, 0 to 830
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Unidad de Compra                 831 non-null    str
 1   ID Proyecto                      831 non-null    str
 2   Tipo Proyecto                    831 non-null    str
 3   Estado Proyecto                  831 non-null    str
 4   Código presupuestario            830 non-null    object
 5   Nombre Proyecto                  831 non-null    str
 6   Descripción Proyecto             831 non-null    str
 7   Cantidad de Ítems                831 non-null    int64
 8   Nombre ítem                      831 non-null    str
 9   Tipo compra                      831 non-null    int64
 10  Cantidad Productos               831 non-null    int64
 11  Monto Unitario Ítem              831 non-null    int64
 12  Monto Total Ítem Año 2025        831 non-null    int64
 13  Cantidad OC                      831 non-null    int64
 14  Meses envío OC                   831 non-null    object
 15  Nombre responsable               831 non-null    str
 16  Cargo responsable                831 non-null    str
 17  Teléfono responsable             831 non-null    object
 18  Correo responsable               831 non-null    str
 19  Fecha de Inicio Compra           831 non-null    datetime64[us]
 20  Fecha Publicación PAC 2025       831 non-null    datetime64[us]
 21  Cantidad OC Asociadas Ítem 2025  831 non-null    int64
 22  OC Asociada Item 2025            708 non-null    str
 23  Item De Arraste                  831 non-null    int64
 24  Monto De Arrastre                831 non-null    int64
 25  Meses envio OC de Arraste        183 non-null    datetime64[us]
dtypes: datetime64[us](3), int64(9), object(3), str(11)
memory usage: 490.4+ KB

In [26]:
df_plan_de_compras.dtypes

Unidad de Compra                              str
ID Proyecto                                   str
Tipo Proyecto                                 str
Estado Proyecto                               str
Código presupuestario                      object
Nombre Proyecto                               str
Descripción Proyecto                          str
Cantidad de Ítems                           int64
Nombre ítem                                   str
Tipo compra                                 int64
Cantidad Productos                          int64
Monto Unitario Ítem                         int64
Monto Total Ítem Año 2025                   int64
Cantidad OC                                 int64
Meses envío OC                             object
Nombre responsable                            str
Cargo responsable                             str
Teléfono responsable                       object
Correo responsable                            str
Fecha de Inicio Compra             datetime64[us]
Fecha Publicación PAC 2025         datetime64[us]
Cantidad OC Asociadas Ítem 2025             int64
OC Asociada Item 2025                         str
Item De Arraste                             int64
Monto De Arrastre                           int64
Meses envio OC de Arraste          datetime64[us]
dtype: object

In [27]:
nulos = pd.DataFrame({
    "Cantidad Nulos": df_plan_de_compras.isnull().sum(),
    "Porcentaje Nulos": (
        df_plan_de_compras.isnull().mean() * 100
    ).round(2)
})

nulos = nulos.sort_values(
    "Porcentaje Nulos",
    ascending=False
)

nulos

                                 Cantidad Nulos  Porcentaje Nulos
Meses envio OC de Arraste                   648             77.98
OC Asociada Item 2025                       123             14.80
Código presupuestario                         1              0.12
Tipo Proyecto                                 0              0.00
ID Proyecto                                   0              0.00
Nombre Proyecto                               0              0.00
Descripción Proyecto                          0              0.00
Cantidad de Ítems                             0              0.00
Estado Proyecto                               0              0.00
Unidad de Compra                              0              0.00
Tipo compra                                   0              0.00
Nombre ítem                                   0              0.00
Cantidad Productos                            0              0.00
Monto Unitario Ítem                           0              0.00
Meses envío OC                                0              0.00
Nombre responsable                            0              0.00
Monto Total Ítem Año 2025                     0              0.00
Cantidad OC                                   0              0.00
Teléfono responsable                          0              0.00
Cargo responsable                             0              0.00
Correo responsable                            0              0.00
Fecha de Inicio Compra                        0              0.00
Cantidad OC Asociadas Ítem 2025               0              0.00
Fecha Publicación PAC 2025                    0              0.00
Item De Arraste                               0              0.00
Monto De Arrastre                             0              0.00

In [28]:
cantidad_duplicados = df_plan_de_compras.duplicated().sum()

print(f"Registros duplicados: {cantidad_duplicados}")

Registros duplicados: 0

In [29]:
valores_unicos = df_plan_de_compras.nunique().sort_values()

valores_unicos

Cantidad Productos                   1
Estado Proyecto                      2
Tipo Proyecto                        2
Item De Arraste                      2
Cantidad de Ítems                    3
Fecha Publicación PAC 2025           4
Tipo compra                          6
Cantidad OC                          8
Meses envio OC de Arraste           10
Cantidad OC Asociadas Ítem 2025     11
Unidad de Compra                    16
Fecha de Inicio Compra              41
Meses envío OC                      59
Correo responsable                  64
Código presupuestario               73
Monto De Arrastre                   77
Cargo responsable                   81
Nombre responsable                  85
Teléfono responsable                96
Monto Total Ítem Año 2025          181
Monto Unitario Ítem                210
Descripción Proyecto               297
Nombre ítem                        317
ID Proyecto                        326
Nombre Proyecto                    328
OC Asociada Item 2025              657
dtype: int64

In [30]:
df_plan_de_compras["Tipo Proyecto"].value_counts()

Tipo Proyecto
Proyecto operacional    613
Proyecto estratégico    218
Name: count, dtype: int64

In [31]:
df_plan_de_compras["Tipo Proyecto"].value_counts(normalize=True).mul(100).round(2)

Tipo Proyecto
Proyecto operacional    73.77
Proyecto estratégico    26.23
Name: proportion, dtype: float64

In [32]:
df_plan_de_compras["Estado Proyecto"].value_counts()

Estado Proyecto
Actualizado    648
Publicado      183
Name: count, dtype: int64

In [33]:
df_plan_de_compras["Unidad de Compra"].value_counts()

Unidad de Compra
Ministerio de Vivienda y Urbanismo(766)    684
SEREMI MINVU V REGION                       30
SEREMI MINVU III REGION                     25
SEREMI MINVU VI REGION                      20
SEREMI IV REGION                            14
SEREMI MINVU REGION ARICA Y PARINACOTA       9
SEREMI MINVU XI REGION                       8
SEREMI MINVU II REGION                       8
SEREMI MINVU I REGION                        7
SEREMI VIII REGION                           6
Seremi-Minvu XII Región                      6
SEREMI MINVU VII REGION                      4
SERVICIO DE BIENESTAR MINVU SERVIU           4
SEREMI MINVU RM                              3
SEREMI ÑUBLE-REGIÓN XVI                      2
SEREMI IX REGION                             1
Name: count, dtype: int64

In [34]:
df_plan_de_compras["Tipo compra"].value_counts().sort_index()

Tipo compra
1    159
2      4
3     20
4     83
5     79
6    486
Name: count, dtype: int64

In [36]:
columnas_montos = [
    "Monto Unitario Ítem",
    "Monto Total Ítem Año 2025",
    "Monto De Arrastre"
]

df_plan_de_compras[columnas_montos].describe()

       Monto Unitario Ítem  Monto Total Ítem Año 2025  Monto De Arrastre
count         8.310000e+02               8.310000e+02       8.310000e+02
mean          1.085214e+08               1.014853e+08       6.139761e+06
std           2.036220e+08               2.024663e+08       3.466941e+07
min           9.000000e+04               0.000000e+00       0.000000e+00
25%           4.200000e+06               3.000000e+06       0.000000e+00
50%           4.000000e+07               3.500000e+07       0.000000e+00
75%           2.020000e+08               2.020000e+08       0.000000e+00
max           4.839000e+09               4.839000e+09       6.747510e+08

In [38]:
df_plan_de_compras[columnas_montos].agg([
    "count",
    "sum",
    "mean",
    "median",
    "min",
    "max"
])

        Monto Unitario Ítem  Monto Total Ítem Año 2025  Monto De Arrastre
count          8.310000e+02               8.310000e+02       8.310000e+02
sum            9.018130e+10               8.433428e+10       5.102141e+09
mean           1.085214e+08               1.014853e+08       6.139761e+06
median         4.000000e+07               3.500000e+07       0.000000e+00
min            9.000000e+04               0.000000e+00       0.000000e+00
max            4.839000e+09               4.839000e+09       6.747510e+08

In [39]:
for columna in columnas_montos:
    cantidad_negativos = (df_plan_de_compras[columna] < 0).sum()
    print(f"{columna}: {cantidad_negativos} valores negativos")

Monto Unitario Ítem: 0 valores negativos
Monto Total Ítem Año 2025: 0 valores negativos
Monto De Arrastre: 0 valores negativos

In [43]:
columnas_cantidad = [
    "Cantidad de Ítems",
    "Cantidad Productos",
    "Cantidad OC",
    "Cantidad OC Asociadas Ítem 2025"
]

df_plan_de_compras[columnas_cantidad].describe()

,Cantidad de Ítems,Cantidad Productos,Cantidad OC,Cantidad OC Asociadas Ítem 2025
count,831.000000,831.0,831.000000,831.000000
mean,1.199759,1.0,1.344164,125.756919
std,0.414845,0.0,1.263753,155.041024
min,1.000000,1.0,1.000000,0.000000
25%,1.000000,1.0,1.000000,1.000000
50%,1.000000,1.0,1.000000,4.000000
75%,1.000000,1.0,1.000000,321.000000
max,3.000000,1.0,12.000000,321.000000